-- MySQL Script generated by MySQL Workbench
-- dom 29 out 2023 15:40:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`tb_user` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(256) NOT NULL,
  `password` VARCHAR(1024) NOT NULL,
  `email` VARCHAR(512) NOT NULL,
  `authorities` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `biblioteca`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`tb_group` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `username` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`tb_emprestimo` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataemprestimo` DATE NULL DEFAULT NULL,
  `datadevolucao` DATE NULL DEFAULT NULL,
  `livro_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprestimo_livro_idx` (`livro_id` ASC) VISIBLE,
  INDEX `fk_emprestimo_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_livro`
    FOREIGN KEY (`livro_id`)
    REFERENCES `biblioteca`.`tb_livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `biblioteca`.`tb_pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`tb_livro` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `emprestado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`tb_pessoa` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert in Tables`
-- -----------------------------------------------------

-- -----------------------------------------------------
-- User
-- -----------------------------------------------------
INSERT INTO `biblioteca`.`tb_user` (`username`, `password`, `email`, `authorities`)
VALUES 
    ("jhon", "$2a$12$xgG4AjFe4WNDbotwOs1w3e.1e3/iZOdyEdui2fQ01J0Vk5wRsyQf6", "jhon@biblioteca.com", "user");

-- -----------------------------------------------------
-- Group
-- -----------------------------------------------------
INSERT INTO `biblioteca`.`tb_group` (`name`, `username`)
VALUES 
    ("user", "jhon");

-- -----------------------------------------------------
-- Pessoa
-- -----------------------------------------------------
INSERT INTO `biblioteca`.`tb_pessoa` (`nome`)
VALUES 
    ("bajinho"),
    ("Maria");

-- -----------------------------------------------------
-- Livro
-- -----------------------------------------------------
INSERT INTO `biblioteca`.`tb_livro` (`titulo`, `autor`, `emprestado`)
VALUES ("Java Para Leigos", " Barry Burd", 1);

-- -----------------------------------------------------
-- Emprestimo
-- -----------------------------------------------------
INSERT INTO `biblioteca`.`tb_emprestimo` (`dataemprestimo`, `livro_id`, `pessoa_id`)
VALUES ('2024-05-11', 1, 1);

-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`view_emprestimo` ;

CREATE VIEW `biblioteca`.`view_emprestimo` 
AS select 
    `biblioteca`.`tb_emprestimo`.`id` AS `id`,
    `biblioteca`.`tb_emprestimo`.`livro_id` AS `livro_id`,
    `biblioteca`.`tb_emprestimo`.`pessoa_id` AS `pessoa_id`,
    `biblioteca`.`tb_emprestimo`.`dataemprestimo` AS `dataemprestimo`,
    `biblioteca`.`tb_emprestimo`.`datadevolucao` AS `datadevolucao`,
    `biblioteca`.`tb_pessoa`.`nome` AS `nome`,
    `biblioteca`.`tb_livro`.`titulo` AS `titulo`,
    `biblioteca`.`tb_livro`.`autor` AS `autor` 
from 
    ((`biblioteca`.`tb_emprestimo` join `biblioteca`.`tb_pessoa`) join `biblioteca`.`tb_livro`) 
where 
    ((`biblioteca`.`tb_emprestimo`.`pessoa_id` = `biblioteca`.`tb_pessoa`.`id`) 
and (`biblioteca`.`tb_emprestimo`.`livro_id` = `biblioteca`.`tb_livro`.`id`));
